### ISSUE TITLE
Prepare User Dashboard v1.0 according to the new design

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-user-dashboard#110]
See here:
https://www.figma.com/file/Xis7MP81TIpPj1MWgbebN9/Dashboard-2?node-id=0%3A2670&t=B7NpRFhPJFJPh4TA-0

Main points:
- [x] Fix the Video widget
- [x] Pin proper numbers to the "EOSC in NUmbers" widget
- [x] Move "EOSC News" to the right panel and represent it as a widget 
- [x] Add left panel with Feed, Profile Settings, and Favorites
- [x] Move "Your profile" to the left Panel (Your profile should link to the Profile in MP: https://marketplace.eosc-portal.eu/profile )
- [x]  Move the "Communities" widget to the right panel and fix them (now we can't click on the widget, it doesn't work)
- [x] Represent "Add project" as a widget at the top (see Figma)
- [x] Remove the upper navigation:
![image](https://user-images.githubusercontent.com/43000481/218437505-eec62c24-d4e8-409f-af98-ceaf9fd343a1.png)

**Comment by tomaszandel** [comment]
done
