### ISSUE TITLE
Add evaluation panel for recommendations in the User Dashboard

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-user-dashboard#116]
According to the design add the possibility to evaluate the recommendation:
https://www.figma.com/file/Xis7MP81TIpPj1MWgbebN9/Dashboard-2?node-id=260%3A5501&t=xCRZU4TeRWMVKTh9-1

- [x] As a User I can dislike the recommendation (proper user action is sent, but nothing happens with the recommendation, the user can still see it)
- [x] As a User I can provide additional feedback about the recommendation

@tomaszandel @michal-szostak I need the technical specification of what will be sent to the databus 

Note 18.05: Poznań reports that the functionality is ready on their side

Additional acceptance criteria (after call with Poznań):
- [ ] As a User I can click thumb down " Show less like this" to dislike a recommendation and system will overlay the resource by the black colour. I can undo my action or send feedback to the system. After the refresh of a website, disliked resource will disappear

Figma:
https://www.figma.com/file/Xis7MP81TIpPj1MWgbebN9/Dashboard-2?type=design&node-id=679-25587&t=3pAtNkLRD9XcYmS1-0

**Comment by tomaszandel** [comment]
aai_uid: string, # zalogowany uzytkownik
unique_id: string, # niezalogowany uzytkownik z ciasteczka
client_id: string, # search_service albo user_dashboard,
timestamp: string,
visit_id: string, # TO SAMO CO ZOSTAŁO WYSŁANE DO REQUESTU O REKOMENDACJE
page_id: string, # np. /my_dashboard
panel_id: string,
resource_id: string,
resource_type: string,
action: string, # np. dislike, survey? 
reason: object, # json z ankiety albo None jesli nie bylo ankiety

**Comment by tomaszandel** [comment]
Create the one for SS as separate ticket, or just convert it into a separate issue
