### ISSUE TITLE
HTML sanitization in the recommendation box

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-user-dashboard#125]
Acceptance criteria:
- [ ] As a User I want to see a clear description of the recommended product/service 

Proposed sanitization scope:

strip away all tags which are not `b`, `strong`, `i`, `br`, `p`. For description `h...` tags are also not recommended.

I would suggest iterative process when we strip almost all tags (except simple formatting, break lines, etc) in description and then see what else should we leave. That's why sanitization method should be easily extendable with new tags to keep. All attributes should be stripped.

**Comment by tomaszandel** [comment]
done
