### ISSUE TITLE
Landing page - final adjustments

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/eosc-user-dashboard#131]
- [ ] Add link to button "Go to Provider's Hub" - https://providers.eosc-portal.eu/
- [ ] Change Create a "Reseach project" to "Create a project"
Add link to button "Create a project"- https://marketplace.eosc-portal.eu/projects/
![image](https://user-images.githubusercontent.com/59872096/228790732-d3ce2c0c-738c-4f3b-a9f2-09b15c6dea75.png)

- [ ] Add link to "My EOSC Dashborad" - https://my.eosc-portal.eu/
![image](https://user-images.githubusercontent.com/59872096/228791748-d8b6c03b-9904-421a-a68b-7d590e7e7d2c.png)

- [ ] Add links to communities card [all card should be clicable]
EOSC-Life open digital space for life sciences - https://www.eosc-life.eu/
ESCAPE – the consistent European research infrastructure ecosystem - https://projectescape.eu/
ENVRI Fair – the way to understanding of the Earth System - https://envri.eu/
SSHOC – towards the complete SSH ecosystem - https://www.sshopencloud.eu/
PaNOSC - adopting FAIR data practices at photon and neutron sources - https://www.panosc.eu/

![image](https://user-images.githubusercontent.com/59872096/228792218-dbb03b25-f53c-4634-9657-27618c919112.png)

- [x] Change text on widgetu
![image](https://user-images.githubusercontent.com/59872096/228795947-afd9d3da-5e8f-41a1-aad7-6de0bf16fa86.png)
to : 

Create a unique project within your scientific discipline. With this feature, you can save and aggregate your favorite services to create a knowledge base from available EOSC resources. Adding the project will help you organize your services a into logical blocks and gain support in the scope of the created idea.

**Comment by eldenkat** [comment]
Create a unique project within your scientific discipline. With this feature, you can save and aggregate your favorite services to create a knowledge base from available EOSC resources. Adding the project will help you organize your services a into logical blocks and gaining support in the scope of the created idea.
