### ISSUE TITLE
Hide "My projects" widget and add the link to the project on the left side bar

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-user-dashboard#134]
As a scope of this issue:
- [ ] Hide (as we will use it in the future)  "My projects" widget
- [ ]  Add the link ( https://marketplace.eosc-portal.eu/projects ) to the project on the left sidebar according to: https://www.figma.com/file/Xis7MP81TIpPj1MWgbebN9/Dashboard-2?node-id=130%3A4676&t=FQsiubWNcX4NeZeC-1

**Comment by tomaszandel** [comment]
done

**Comment by agpul** [comment]
where? ;)
