### ISSUE TITLE
Create "Your Profile Widget"

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-user-dashboard#53]
**Widget**
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/4ccaabc5-c280-425a-a5dd-9534a9273427)

See reference: https://www.figma.com/file/RHmHoBRvx1oon6JwKK3Iaf/EOSC-Dashboard?node-id=88%3A5007

**Acceptance Criteria**
- [x] As a user I can see te "Your Profile" Widget in the upper right corner od the website
- [ ] As a User I can see the space for a photo or avatar (taken from AAI/my EOSC Marketplace profile)
- [x] As a user I can see my name and surname (information taken from AAI)
- [x] As a user I can see my email address displayed below name and surnnme (information taken from AAI)
- [ ] As a user I can see the number of my favourite resources 
- [ ] As a user I am able to edit my profile via **marketplace.eosc-portal.eu/profile**, by by clicking on the "Edit profile" option located in the upper right corner of the widget.

**Comment by tomaszandel** [comment]
marketplace.eosc-portal.eu/profile.  as well as account-service from userApi does not have any images, moreover seems like official profile link is hidden in account-service reply, so i used this edit link. To be clarified, also Fav Resources is not accessible anywhere, shall we add it somehow and link it ? Who is going to store it and where ?
