### ISSUE TITLE
Create "EOSC in Numbers" widget

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-user-dashboard#54]
**Widget:**
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/f25bb9d3-5b2d-402d-a956-74cff0998511)

**Endpoint:**
 https://api.eosc-search-service.grid.cyfronet.pl

**Acceptance criteria**
- [ ] As a user I can see the "EOSC in Numbers" widget with a short description
- [ ] As a user I can see the box related to Services with the proper icon and the number of them
- [ ] As a user I can see the box related to Publication with the proper icon and the number of them
- [ ] As a user I can see the box related to Training with the proper icon and the number of them
- [ ] As a user I can see the box related to Software with the proper icon and the number of them
- [ ] As a user I can see the box related to Data with the proper icon and the number of them
- [ ] As a user I can see the box related to Datasets with the proper icon and the number of them

**Comment by danielkryska** [comment]
To fetch data we're using the local net available endpoint to Search Service. In case of getting more knowledge about the endpoint and how to use it ask @michal-szostak, @danielkryska, and/or @Michal-Kolomanski

**Comment by Michal-Kolomanski** [comment]
> To fetch data we're using the local net available endpoint to Search Service. In case of getting more knowledge about the endpoint and how to use it ask @michal-szostak, @danielkryska, and/or @Michal-Kolomanski

We are getting some statistics regarding OAG resources [stats](https://docs.google.com/spreadsheets/d/1kbh1ndrM2eePksVhlxZV3XTD3fHYCzN72kpAgmbVc40/edit#gid=0). It may be useful here

**Comment by aleksandrahojszyk** [comment]
<img width="645" alt="Zrzut ekranu 2022-10-31 o 15 24 10" src="https://user-images.githubusercontent.com/49695272/199030962-928551d5-8265-45f1-930a-4790bcf878ab.png">

**Comment by aleksandrahojszyk** [comment]
![articles book](https://user-images.githubusercontent.com/49695272/199031079-9b9b8193-6db2-4cf3-87fb-57ba1377442e.svg)
![cloud share ](https://user-images.githubusercontent.com/49695272/199031088-6a79501a-b93d-4788-b4dd-a01cb41f90fd.svg)
![learning](https://user-images.githubusercontent.com/49695272/199031092-21bd05dd-fec1-4244-8a42-b564d182f70a.svg)
![settings](https://user-images.githubusercontent.com/49695272/199031094-fb8c70c9-ce04-4b92-bfab-343ba43b889f.svg)

**Comment by danielkryska** [comment]
Start with template availabel at `ui/apps/ui/src/app/components/widgets/eosc-numbers.component.ts`
