### ISSUE TITLE
Create "Upcoming Events" widget

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-user-dashboard#55]
**The widget that I am referring to:** 
![image](https://user-images.githubusercontent.com/43000481/197999285-97612c2e-5aea-49ab-b40d-629d9c4cdbb6.png)
**Specification:**
[EOSC Dashboard v2.pdf](https://github.com/cyfronet-fid/eosc-user-dashboard/files/9868421/EOSC.Dashboard.v2.pdf)
**Design system:**
https://www.figma.com/file/RHmHoBRvx1oon6JwKK3Iaf/EOSC-Dashboard?node-id=233%3A4733

** Endpoint**
https://eosc-portal.eu/events-json-date/2022-03-01--2022-12-01

**Acceptance criteria**
- [ ] As a user I can see the "Upcoming Events" widget
- [ ] As a user I can see two upcoming events presented at the same time one by one
- [ ]  As a user I can see the picture, title, and date of every event
- [ ] As a user I can click on the event's title and be redirected to the specific event website
- [ ] As a user I can see two next events changing automatically every 10 sec
- [ ] As a user I can change two displayed events manually using arrows situated on the bottom right corner of the widget
- [ ] As a user I can expand the list of events using the "Show all" button situated in the upper right corner, which redirects me to: https://eosc-portal.eu/media/events

**Comment by tomaszandel** [comment]
starting point
ui/apps/ui/src/app/components/widgets/upcoming-events.component.ts
