### ISSUE TITLE
"Create Have an impact" widget

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-user-dashboard#56]
**A widget that I am reffering**
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/7795f01a-f6f1-4b12-989c-dc5a502c3bb2)
**Specification**
[EOSC Dashboard v2.pdf](https://github.com/cyfronet-fid/eosc-user-dashboard/files/9868391/EOSC.Dashboard.v2.pdf)
**Design System**
https://www.figma.com/file/RHmHoBRvx1oon6JwKK3Iaf/EOSC-Dashboard?node-id=233%3A4733
**Acceptance criteria**
- [x]  As a user I can see to "Have an impact" widget
- [x] As a user I can see the short description, graphics, and the button "Contact us"
- [x] As a user I can click on the button "Contact us" which opens the contact form where I can write the email to contact@eosc-portal.eu

**Comment by tomaszandel** [comment]
done, ready for tests, (excluding mobile)
