### ISSUE TITLE
Implementation of the Communities widgets into the User Dashboard landing page.

### ISSUE THREAD

**Issue by eldenkat** [cyfronet-fid/eosc-user-dashboard#89]
**Widgets**
![Zrzut ekranu 2022-11-23 o 14.35.00.png](https://images.zenhubusercontent.com/632189b6254ebf7302133662/f552d448-8522-48ed-a5f3-d92fa8a55e86)

**Specification**
[https://app.zenhub.com/files/135438250/75b7e475-f32b-4fad-807d-70b1582796af/download](https://app.zenhub.com/files/135438250/75b7e475-f32b-4fad-807d-70b1582796af/download)

**Design System**
https://www.figma.com/file/RHmHoBRvx1oon6JwKK3Iaf/EOSC-Dashboard?node-id=798%3A7990&t=lQF78xNswIdWhLro-0

**Acceptance Criteria**
- [x] As a user I can see a a horizontal slider widgets titled "EOSC Communities" at the top of the User Dashboard
- [x] As a user I can see the left and the right arrow right after the EOC Communities caption
- [x] As a user I can click the left and right arrow in order to move the slider and see the other available widgets.
- [x] As a user, using the slider, I can see that there are 5 widgets available (EOSC-Life, SSHOC, ESCAPE, PaNOSC and ENVRI Fair)
- [x] As a user ,at the same time, I can  see three full widgets and a fragment of the fourth widget out of five available.
- [x] As a user I can see that each available communities widget consists od the picture, short description and active "Read more" button.
- [x] As a user, in each widget I can see the picture on the left side of the widget, description on the right side and the "Read more" button below the description 
- [x] As a user I can click "Read more" in order to be redirected to the chosen Community webside.

**Comment by tomaszandel** [comment]
btw, that zenhub looks not operational, not able to download it ;)

**Comment by tomaszandel** [comment]
done (excluding mobile)

**Comment by tomaszandel** [comment]
implemented
